var res = {
    brick1x1_png: "res/brick1x1.png",
    brick2x1_png: "res/brick2x1.png",
    brick3x1_png: "res/brick3x1.png",
    brick4x1_png: "res/brick4x1.png",
    brick4x2_png: "res/brick4x2.png",
    ground_png: "res/ground.png",
    player_png: "res/player3.png",
    terrain_png: "res/terrain.png",
    background_png: "res/background2.png",
    background_png2: "res/kari.png",
    map00_tmx: "res/map00.tmx",
    map_test_tmx: "res/map_test.tmx",
    object_tsx: "res/object.tsx",
    enemy_tsx: "res/enemy.tsx",
    terrain_tsx: "res/terrain.tsx",
    object_png: "res/object.png",
    enemy_png: "res/enemy.png",
    pickup_coin_mp3: "res/pickup_coin.mp3",
    food_mp3: "res/food.mp3",
    landing_mp3: "res/landing.mp3",
    jump_mp3: "res/jump.mp3",
    decide_mp3: "res/decide.mp3",
    complete_mp3: "res/complete.mp3",
    start_mp3: "res/start.mp3",
    explode_mp3: "res/explode.mp3",
    player_sheet: "res/p.png",
    player_plist: "res/player.plist",
    rightbtn_png: "res/right.png",
    leftbtn_png: "res/left.png",
    jumpbtn_png: "res/jump.png",
    clear_png: "res/clear.png",
    exit2_png: "res/exit2.png",
    shot_png: "res/mahou.png",
    title_png: "res/t_bg2.png",
    start_png: "res/start2.png",
    game_title_png: "res/title3.png",
    gameover_png:"res/gameoverkari2.png",
    exit_png: "res/exit.png",
    heal_mp3: "res/heal01.mp3",
    hit_mp3: "res/hit01.mp3",
    bgm_main_mp3:"res/tw070.mp3",
    title_bgm: "res/tw043.mp3",
    gameover_mp3: "res/st011.mp3",
    clear_mp3: "res/tw006.mp3",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
